import 'package:flutter/material.dart';
import '../services/theme_manager.dart';

class TerminalThemes {
  TerminalThemes._();

  static TerminalTheme get cyberpunk => TerminalTheme(
    name: 'Cyberpunk',
    backgroundColor: const Color(0xFF0D0221),
    foregroundColor: const Color(0xFF00F0FF),
    cursorColor: const Color(0xFFFF00FF),
    selectionColor: const Color(0xFF00F0FF).withOpacity(0.3),
    black: const Color(0xFF1A0B2E),
    red: const Color(0xFFFF0055),
    green: const Color(0xFF00FF66),
    yellow: const Color(0xFFFFEE00),
    blue: const Color(0xFF0088FF),
    magenta: const Color(0xFFFF00FF),
    cyan: const Color(0xFF00F0FF),
    white: const Color(0xFFCCFFFF),
    brightBlack: const Color(0xFF2A1B3E),
    brightRed: const Color(0xFFFF3377),
    brightGreen: const Color(0xFF33FF88),
    brightYellow: const Color(0xFFFFFF33),
    brightBlue: const Color(0xFF33AAFF),
    brightMagenta: const Color(0xFFFF33FF),
    brightCyan: const Color(0xFF33FFFF),
    brightWhite: const Color(0xFFFFFFFF),
    searchHitBackground: const Color(0xFFFF00FF),
    searchHitForeground: Colors.white,
    fontWeight: FontWeight.normal,
  );

  static TerminalTheme get matrix => TerminalTheme(
    name: 'Matrix',
    backgroundColor: Colors.black,
    foregroundColor: const Color(0xFF00FF00),
    cursorColor: const Color(0xFF00FF00),
    selectionColor: const Color(0xFF00FF00).withOpacity(0.3),
    black: const Color(0xFF0A0A0A),
    red: const Color(0xFF44FF44),
    green: const Color(0xFF00FF00),
    yellow: const Color(0xFFAAFF00),
    blue: const Color(0xFF00AA00),
    magenta: const Color(0xFF55FF55),
    cyan: const Color(0xFF88FF88),
    white: const Color(0xFFAAFFAA),
    brightBlack: const Color(0xFF222222),
    brightRed: const Color(0xFF66FF66),
    brightGreen: const Color(0xFF33FF33),
    brightYellow: const Color(0xFFBBFF33),
    brightBlue: const Color(0xFF33BB33),
    brightMagenta: const Color(0xFF77FF77),
    brightCyan: const Color(0xFFAAFFAA),
    brightWhite: const Color(0xFFFFFFFF),
    searchHitBackground: const Color(0xFF00FF00),
    searchHitForeground: Colors.black,
    fontWeight: FontWeight.normal,
  );

  static TerminalTheme get ocean => TerminalTheme(
    name: 'Ocean',
    backgroundColor: const Color(0xFF001830),
    foregroundColor: const Color(0xFFAADDFF),
    cursorColor: const Color(0xFF44AAFF),
    selectionColor: const Color(0xFF44AAFF).withOpacity(0.3),
    black: const Color(0xFF001020),
    red: const Color(0xFFFF6B6B),
    green: const Color(0xFF4ECDC4),
    yellow: const Color(0xFFFFE66D),
    blue: const Color(0xFF44AAFF),
    magenta: const Color(0xFF9B59B6),
    cyan: const Color(0xFF00DDFF),
    white: const Color(0xFFBBEEFF),
    brightBlack: const Color(0xFF002840),
    brightRed: const Color(0xFFFF8888),
    brightGreen: const Color(0xFF6FEEDC),
    brightYellow: const Color(0xFFFFF088),
    brightBlue: const Color(0xFF66BBFF),
    brightMagenta: const Color(0xFFBB77CC),
    brightCyan: const Color(0xFF33EEFF),
    brightWhite: const Color(0xFFFFFFFF),
    searchHitBackground: const Color(0xFFFFE66D),
    searchHitForeground: Colors.black,
    fontWeight: FontWeight.normal,
  );

  static TerminalTheme get sunset => TerminalTheme(
    name: 'Sunset',
    backgroundColor: const Color(0xFF1A0A00),
    foregroundColor: const Color(0xFFFFCCAA),
    cursorColor: const Color(0xFFFF8844),
    selectionColor: const Color(0xFFFF8844).withOpacity(0.3),
    black: const Color(0xFF2A1505),
    red: const Color(0xFFFF4444),
    green: const Color(0xFF88CC44),
    yellow: const Color(0xFFFFAA22),
    blue: const Color(0xFF6688FF),
    magenta: const Color(0xFFFF66AA),
    cyan: const Color(0xFF44DDCC),
    white: const Color(0xFFDDCCBB),
    brightBlack: const Color(0xFF3A2515),
    brightRed: const Color(0xFFFF6666),
    brightGreen: const Color(0xFFAADD66),
    brightYellow: const Color(0xFFFFCC44),
    brightBlue: const Color(0xFF88AAFF),
    brightMagenta: const Color(0xFFFF88CC),
    brightCyan: const Color(0xFF66EEDD),
    brightWhite: const Color(0xFFFFEEDD),
    searchHitBackground: const Color(0xFFFFAA22),
    searchHitForeground: Colors.black,
    fontWeight: FontWeight.normal,
  );

  static TerminalTheme get monochrome => TerminalTheme(
    name: 'Monochrome',
    backgroundColor: Colors.black,
    foregroundColor: Colors.white,
    cursorColor: Colors.white,
    selectionColor: Colors.white.withOpacity(0.3),
    black: const Color(0xFF111111),
    red: const Color(0xFFCCCCCC),
    green: const Color(0xFFAAAAAA),
    yellow: const Color(0xFFEEEEEE),
    blue: const Color(0xFF888888),
    magenta: const Color(0xFFBBBBBB),
    cyan: const Color(0xFF999999),
    white: const Color(0xFFFFFFFF),
    brightBlack: const Color(0xFF222222),
    brightRed: const Color(0xFFDDDDDD),
    brightGreen: const Color(0xFFBBBBBB),
    brightYellow: const Color(0xFFFFFFFF),
    brightBlue: const Color(0xFF999999),
    brightMagenta: const Color(0xFFCCCCCC),
    brightCyan: const Color(0xFFAAAAAA),
    brightWhite: const Color(0xFFFFFFFF),
    searchHitBackground: Colors.white,
    searchHitForeground: Colors.black,
    fontWeight: FontWeight.normal,
  );

  static TerminalTheme get zenburn => TerminalTheme(
    name: 'Zenburn',
    backgroundColor: const Color(0xFF3F3F3F),
    foregroundColor: const Color(0xFFDCDCCC),
    cursorColor: const Color(0xFF73635A),
    selectionColor: const Color(0xFF21322A),
    black: const Color(0xFF4D4D4D),
    red: const Color(0xFFFF6B6B),
    green: const Color(0xFF8FB28F),
    yellow: const Color(0xFFF0DFAF),
    blue: const Color(0xFF8CD0D3),
    magenta: const Color(0xFFDC8CC3),
    cyan: const Color(0xFF93E0E3),
    white: const Color(0xFFDCDCCC),
    brightBlack: const Color(0xFF709080),
    brightRed: const Color(0xFFDCA3A3),
    brightGreen: const Color(0xFF9FC59F),
    brightYellow: const Color(0xFFEFEF8F),
    brightBlue: const Color(0xFFBCA3A3),
    brightMagenta: const Color(0xFFEC93D3),
    brightCyan: const Color(0xFFA3D4E3),
    brightWhite: const Color(0xFFFFFFFF),
    searchHitBackground: const Color(0xFF385F38),
    searchHitForeground: const Color(0xFFDCDCCC),
    fontWeight: FontWeight.normal,
  );

  static TerminalTheme get dracula => TerminalTheme(
    name: 'Dracula',
    backgroundColor: const Color(0xFF282A36),
    foregroundColor: const Color(0xFFF8F8F2),
    cursorColor: const Color(0xFFBD93F9),
    selectionColor: const Color(0xFF44475A),
    black: const Color(0xFF21222C),
    red: const Color(0xFFFF5555),
    green: const Color(0xFF50FA7B),
    yellow: const Color(0xFFF1FA8C),
    blue: const Color(0xFFBD93F9),
    magenta: const Color(0xFFFF79C6),
    cyan: const Color(0xFF8BE9FD),
    white: const Color(0xFFF8F8F2),
    brightBlack: const Color(0xFF6272A4),
    brightRed: const Color(0xFFFF6E6E),
    brightGreen: const Color(0xFF69FF94),
    brightYellow: const Color(0xFFFFFFA5),
    brightBlue: const Color(0xFFD6ACFF),
    brightMagenta: const Color(0xFFFF92DF),
    brightCyan: const Color(0xFFA4FFFF),
    brightWhite: const Color(0xFFFFFFFF),
    searchHitBackground: const Color(0xFF50FA7B),
    searchHitForeground: const Color(0xFF282A36),
    fontWeight: FontWeight.normal,
  );

  static TerminalTheme get nord => TerminalTheme(
    name: 'Nord',
    backgroundColor: const Color(0xFF2E3440),
    foregroundColor: const Color(0xFFD8DEE9),
    cursorColor: const Color(0xFF81A1C1),
    selectionColor: const Color(0xFF434C5E),
    black: const Color(0xFF3B4252),
    red: const Color(0xFFBF616A),
    green: const Color(0xFFA3BE8C),
    yellow: const Color(0xFFEBCB8B),
    blue: const Color(0xFF81A1C1),
    magenta: const Color(0xFFB48EAD),
    cyan: const Color(0xFF88C0D0),
    white: const Color(0xFFE5E9F0),
    brightBlack: const Color(0xFF4C566A),
    brightRed: const Color(0xFFBF616A),
    brightGreen: const Color(0xFFA3BE8C),
    brightYellow: const Color(0xFFEBCB8B),
    brightBlue: const Color(0xFF81A1C1),
    brightMagenta: const Color(0xFFB48EAD),
    brightCyan: const Color(0xFF8FBCBB),
    brightWhite: const Color(0xFFECEFF4),
    searchHitBackground: const Color(0xFF88C0D0),
    searchHitForeground: const Color(0xFF2E3440),
    fontWeight: FontWeight.normal,
  );

  static TerminalTheme get solarizedDark => TerminalTheme(
    name: 'Solarized Dark',
    backgroundColor: const Color(0xFF002B36),
    foregroundColor: const Color(0xFF839496),
    cursorColor: const Color(0xFF93A1A1),
    selectionColor: const Color(0xFF073642),
    black: const Color(0xFF073642),
    red: const Color(0xFFDC322F),
    green: const Color(0xFF859900),
    yellow: const Color(0xFFB58900),
    blue: const Color(0xFF268BD2),
    magenta: const Color(0xFFD33682),
    cyan: const Color(0xFF2AA198),
    white: const Color(0xFFEEE8D5),
    brightBlack: const Color(0xFF002B36),
    brightRed: const Color(0xFFCB4B16),
    brightGreen: const Color(0xFF586E75),
    brightYellow: const Color(0xFF657B83),
    brightBlue: const Color(0xFF839496),
    brightMagenta: const Color(0xFF6C71C4),
    brightCyan: const Color(0xFF93A1A1),
    brightWhite: const Color(0xFFFDF6E3),
    searchHitBackground: const Color(0xFFB58900),
    searchHitForeground: const Color(0xFF002B36),
    fontWeight: FontWeight.normal,
  );

  static List<TerminalTheme> get allThemes => [
    cyberpunk,
    matrix,
    ocean,
    sunset,
    monochrome,
    zenburn,
    dracula,
    nord,
    solarizedDark,
  ];

  static TerminalTheme? getByName(String name) {
    try {
      return allThemes.firstWhere((t) => t.name.toLowerCase() == name.toLowerCase());
    } catch (e) {
      return null;
    }
  }

  static TerminalTheme get defaultTheme => cyberpunk;

  static List<String> get themeNames => allThemes.map((t) => t.name).toList();
}
