import 'package:flutter/material.dart';
import 'models/tool.dart';

/// ToolRegistry - Central registry containing all 100+ tools
/// Organized by category for easy access and scalability
/// New tools can be added by simply adding a new entry to the list
class ToolRegistry {
  ToolRegistry._();

  /// Complete list of all registered tools (100 tools across 4 categories)
  static final List<Tool> allTools = [
    // ═══════════════════════════════════════════════════════════
    // CATEGORY 1: Network Tools (25 tools)
    // ═══════════════════════════════════════════════════════════
    Tool(
      id: 'port_scanner',
      name: 'Port Scanner',
      arabicName: 'ماسح المنافذ',
      description: 'Scan open ports on a target host using TCP connect scanning',
      arabicDescription: 'مسح المنافذ المفتوحة على هدف باستخدام TCP',
      category: ToolCategory.network,
      icon: Icons.router,
      route: '/tool_runner',
      parameters: {'target': '', 'portRange': '1-1024', 'timeout': '2000'},
    ),
    Tool(
      id: 'subdomain_finder',
      name: 'Subdomain Finder',
      arabicName: 'مكتشف النطاقات الفرعية',
      description: 'Discover subdomains of a target domain using DNS enumeration',
      arabicDescription: 'اكتشاف النطاقات الفرعية لنطاق معين',
      category: ToolCategory.network,
      icon: Icons.account_tree,
      route: '/tool_runner',
      parameters: {'domain': '', 'wordlist': 'common'},
    ),
    Tool(
      id: 'dns_lookup',
      name: 'DNS Lookup',
      arabicName: 'استعلام DNS',
      description: 'Query DNS records (A, AAAA, MX, TXT, NS, CNAME) for a domain',
      arabicDescription: 'الاستعلام عن سجلات DNS لنطاق معين',
      category: ToolCategory.network,
      icon: Icons.dns,
      route: '/tool_runner',
      parameters: {'domain': '', 'recordType': 'A'},
    ),
    Tool(
      id: 'whois',
      name: 'WHOIS Lookup',
      arabicName: 'معلومات Whois',
      description: 'Retrieve WHOIS information for a domain or IP address',
      arabicDescription: 'جلب معلومات WHOIS لنطاق أو IP',
      category: ToolCategory.network,
      icon: Icons.info_outline,
      route: '/tool_runner',
      parameters: {'query': ''},
    ),
    Tool(
      id: 'traceroute',
      name: 'Traceroute',
      arabicName: 'تتبع المسار',
      description: 'Trace the network path to a target host',
      arabicDescription: 'تتبع المسار الشبكي لهدف معين',
      category: ToolCategory.network,
      icon: Icons.route,
      route: '/tool_runner',
      parameters: {'target': '', 'maxHops': '30'},
    ),
    Tool(
      id: 'ping',
      name: 'Ping',
      arabicName: 'اختبار الاتصال',
      description: 'Test connectivity to a host using ICMP echo requests',
      arabicDescription: 'اختبار الاتصال بجهاز باستخدام ICMP',
      category: ToolCategory.network,
      icon: Icons.network_ping,
      route: '/tool_runner',
      parameters: {'target': '', 'count': '4'},
    ),
    Tool(
      id: 'http_headers',
      name: 'HTTP Headers',
      arabicName: 'فاحص رؤوس HTTP',
      description: 'Inspect HTTP response headers from a web server',
      arabicDescription: 'فحص رؤوس HTTP الاستجابة من خادم ويب',
      category: ToolCategory.network,
      icon: Icons.http,
      route: '/tool_runner',
      parameters: {'url': ''},
    ),
    Tool(
      id: 'ssl_checker',
      name: 'SSL Checker',
      arabicName: 'فاحص شهادة SSL',
      description: 'Check SSL/TLS certificate details and expiry',
      arabicDescription: 'فحص تفاصيل وصلاحية شهادة SSL',
      category: ToolCategory.network,
      icon: Icons.https,
      route: '/tool_runner',
      parameters: {'hostname': '', 'port': '443'},
    ),
    Tool(
      id: 'ip_geolocator',
      name: 'IP Geolocator',
      arabicName: 'تحديد موقع IP',
      description: 'Get geographic location information for an IP address',
      arabicDescription: 'تحديد الموقع الجغرافي لعنوان IP',
      category: ToolCategory.network,
      icon: Icons.location_on,
      route: '/tool_runner',
      parameters: {'ip': ''},
    ),
    Tool(
      id: 'mac_vendor_lookup',
      name: 'MAC Vendor Lookup',
      arabicName: 'معرفة بائع MAC',
      description: 'Identify the manufacturer from a MAC address',
      arabicDescription: 'تحديد الشركة المصنعة من عنوان MAC',
      category: ToolCategory.network,
      icon: Icons.memory,
      route: '/tool_runner',
      parameters: {'mac': ''},
    ),
    Tool(
      id: 'wake_on_lan',
      name: 'Wake on LAN',
      arabicName: 'إيقاظ الشبكة',
      description: 'Send Wake-on-LAN magic packet to wake up a device',
      arabicDescription: 'إرسال حزمة إيقاظ لتشغيل جهاز عن بعد',
      category: ToolCategory.network,
      icon: Icons.power_settings_new,
      route: '/tool_runner',
      parameters: {'mac': '', 'broadcast': '255.255.255.255'},
    ),
    Tool(
      id: 'subnet_calculator',
      name: 'Subnet Calculator',
      arabicName: 'حاسبة الشبكات الفرعية',
      description: 'Calculate subnet details from IP and CIDR',
      arabicDescription: 'حساب تفاصيل الشبكة الفرعية من IP وCIDR',
      category: ToolCategory.network,
      icon: Icons.calculate,
      route: '/tool_runner',
      parameters: {'ip': '', 'cidr': '24'},
    ),
    Tool(
      id: 'port_knock',
      name: 'Port Knock',
      arabicName: 'طارق المنافذ',
      description: 'Perform port knocking sequence on a target',
      arabicDescription: 'تنفيذ تسلسل طرق المنافذ على هدف',
      category: ToolCategory.network,
      icon: Icons.door_front_door_outlined,
      route: '/tool_runner',
      parameters: {'target': '', 'sequence': '7000,8000,9000'},
    ),
    Tool(
      id: 'tcp_listener',
      name: 'TCP Listener',
      arabicName: 'مستمع TCP',
      description: 'Create a TCP listener on a specified port',
      arabicDescription: 'إنشاء مستمع TCP على منفذ محدد',
      category: ToolCategory.network,
      icon: Icons.hearing,
      route: '/tool_runner',
      parameters: {'port': '8080'},
    ),
    Tool(
      id: 'udp_sender',
      name: 'UDP Sender',
      arabicName: 'مرسل UDP',
      description: 'Send UDP packets to a target host and port',
      arabicDescription: 'إرسال حزم UDP لهدف معين',
      category: ToolCategory.network,
      icon: Icons.send,
      route: '/tool_runner',
      parameters: {'target': '', 'port': '', 'message': ''},
    ),
    Tool(
      id: 'network_speed_test',
      name: 'Network Speed Test',
      arabicName: 'اختبار سرعة الشبكة',
      description: 'Measure network download and upload speed',
      arabicDescription: 'قياس سرعة التحميل والرفع',
      category: ToolCategory.network,
      icon: Icons.speed,
      route: '/tool_runner',
    ),
    Tool(
      id: 'arp_scanner',
      name: 'ARP Scanner',
      arabicName: 'ماسح ARP',
      description: 'Scan local network using ARP requests',
      arabicDescription: 'مسح الشبكة المحلية باستخدام ARP',
      category: ToolCategory.network,
      icon: Icons.wifi_find,
      route: '/tool_runner',
      parameters: {'subnet': '192.168.1.0/24'},
    ),
    Tool(
      id: 'dhcp_discover',
      name: 'DHCP Discover',
      arabicName: 'مكتشف DHCP',
      description: 'Discover DHCP servers on the local network',
      arabicDescription: 'اكتشاف خوادم DHCP في الشبكة المحلية',
      category: ToolCategory.network,
      icon: Icons.router_outlined,
      route: '/tool_runner',
    ),
    Tool(
      id: 'netbios_scanner',
      name: 'NetBIOS Scanner',
      arabicName: 'ماسح NetBIOS',
      description: 'Scan for NetBIOS names and services',
      arabicDescription: 'مسح أسماء وخدمات NetBIOS',
      category: ToolCategory.network,
      icon: Icons.devices,
      route: '/tool_runner',
      parameters: {'subnet': '192.168.1.0/24'},
    ),
    Tool(
      id: 'upnp_discover',
      name: 'UPnP Discover',
      arabicName: 'مكتشف UPnP',
      description: 'Discover UPnP devices on the network',
      arabicDescription: 'اكتشاف أجهزة UPnP في الشبكة',
      category: ToolCategory.network,
      icon: Icons.cast_connected,
      route: '/tool_runner',
    ),
    Tool(
      id: 'mqtt_client',
      name: 'MQTT Client',
      arabicName: 'عميل MQTT',
      description: 'Connect to and test MQTT brokers',
      arabicDescription: 'الاتصال واختبار وسطاء MQTT',
      category: ToolCategory.network,
      icon: Icons.message,
      route: '/tool_runner',
      parameters: {'broker': '', 'port': '1883', 'topic': ''},
    ),
    Tool(
      id: 'websocket_client',
      name: 'WebSocket Client',
      arabicName: 'عميل WebSocket',
      description: 'Test WebSocket connections and messaging',
      arabicDescription: 'اختبار اتصالات WebSocket',
      category: ToolCategory.network,
      icon: Icons.sync_alt,
      route: '/tool_runner',
      parameters: {'url': '', 'message': ''},
    ),
    Tool(
      id: 'ftp_client',
      name: 'FTP Client',
      arabicName: 'عميل FTP',
      description: 'Connect to FTP servers and browse files',
      arabicDescription: 'الاتصال بخوادم FTP وتصفح الملفات',
      category: ToolCategory.network,
      icon: Icons.folder_open,
      route: '/tool_runner',
      parameters: {'host': '', 'port': '21', 'username': 'anonymous'},
    ),
    Tool(
      id: 'smtp_client',
      name: 'SMTP Client',
      arabicName: 'عميل SMTP',
      description: 'Test SMTP server connectivity and send test emails',
      arabicDescription: 'اختبار اتصال SMTP وإرسال رسائل تجريبية',
      category: ToolCategory.network,
      icon: Icons.email,
      route: '/tool_runner',
      parameters: {'host': '', 'port': '25', 'to': ''},
    ),
    Tool(
      id: 'telnet_client',
      name: 'Telnet Client',
      arabicName: 'عميل Telnet',
      description: 'Connect to telnet servers',
      arabicDescription: 'الاتصال بخوادم Telnet',
      category: ToolCategory.network,
      icon: Icons.terminal,
      route: '/tool_runner',
      parameters: {'host': '', 'port': '23'},
    ),

    // ═══════════════════════════════════════════════════════════
    // CATEGORY 2: Crypto Tools (25 tools)
    // ═══════════════════════════════════════════════════════════
    Tool(
      id: 'md5_hasher',
      name: 'MD5 Hasher',
      arabicName: 'توليد MD5',
      description: 'Generate MD5 hash of input text',
      arabicDescription: 'توليد تجزئة MD5 لنص المدخل',
      category: ToolCategory.crypto,
      icon: Icons.fingerprint,
      route: '/tool_runner',
      parameters: {'input': '', 'mode': 'text'},
    ),
    Tool(
      id: 'sha256_hasher',
      name: 'SHA-256 Hasher',
      arabicName: 'توليد SHA-256',
      description: 'Generate SHA-256 hash of input text',
      arabicDescription: 'توليد تجزئة SHA-256 لنص المدخل',
      category: ToolCategory.crypto,
      icon: Icons.gavel,
      route: '/tool_runner',
      parameters: {'input': '', 'mode': 'text'},
    ),
    Tool(
      id: 'base64_encoder',
      name: 'Base64 Encoder',
      arabicName: 'تشفير Base64',
      description: 'Encode text to Base64',
      arabicDescription: 'ترميز النص إلى Base64',
      category: ToolCategory.crypto,
      icon: Icons.code,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'base64_decoder',
      name: 'Base64 Decoder',
      arabicName: 'فك تشفير Base64',
      description: 'Decode Base64 to text',
      arabicDescription: 'فك ترميز Base64 إلى نص',
      category: ToolCategory.crypto,
      icon: Icons.decode,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'aes_encryptor',
      name: 'AES Encryptor',
      arabicName: 'تشفير AES',
      description: 'Encrypt text using AES-256-CBC',
      arabicDescription: 'تشفير النص باستخدام AES-256-CBC',
      category: ToolCategory.crypto,
      icon: Icons.lock,
      route: '/tool_runner',
      parameters: {'plaintext': '', 'key': '', 'iv': ''},
    ),
    Tool(
      id: 'aes_decryptor',
      name: 'AES Decryptor',
      arabicName: 'فك تشفير AES',
      description: 'Decrypt AES-256-CBC encrypted text',
      arabicDescription: 'فك تشفير نص مشفر بـ AES-256-CBC',
      category: ToolCategory.crypto,
      icon: Icons.lock_open,
      route: '/tool_runner',
      parameters: {'ciphertext': '', 'key': '', 'iv': ''},
    ),
    Tool(
      id: 'rsa_key_generator',
      name: 'RSA Key Generator',
      arabicName: 'مولد مفاتيح RSA',
      description: 'Generate RSA key pairs',
      arabicDescription: 'توليد أزواج مفاتيح RSA',
      category: ToolCategory.crypto,
      icon: Icons.vpn_key,
      route: '/tool_runner',
      parameters: {'keySize': '2048'},
    ),
    Tool(
      id: 'rsa_encryptor',
      name: 'RSA Encryptor',
      arabicName: 'تشفير RSA',
      description: 'Encrypt text using RSA public key',
      arabicDescription: 'تشفير النص باستخدام مفتاح RSA العام',
      category: ToolCategory.crypto,
      icon: Icons.lock_outline,
      route: '/tool_runner',
      parameters: {'plaintext': '', 'publicKey': ''},
    ),
    Tool(
      id: 'rsa_decryptor',
      name: 'RSA Decryptor',
      arabicName: 'فك تشفير RSA',
      description: 'Decrypt text using RSA private key',
      arabicDescription: 'فك تشفير النص باستخدام مفتاح RSA الخاص',
      category: ToolCategory.crypto,
      icon: Icons.lock_open_outlined,
      route: '/tool_runner',
      parameters: {'ciphertext': '', 'privateKey': ''},
    ),
    Tool(
      id: 'bcrypt_hasher',
      name: 'Bcrypt Hasher',
      arabicName: 'تشفير Bcrypt',
      description: 'Hash passwords using Bcrypt',
      arabicDescription: 'تجزئة كلمات المرور باستخدام Bcrypt',
      category: ToolCategory.crypto,
      icon: Icons.password,
      route: '/tool_runner',
      parameters: {'password': '', 'rounds': '10'},
    ),
    Tool(
      id: 'hmac_generator',
      name: 'HMAC Generator',
      arabicName: 'توليد HMAC',
      description: 'Generate HMAC with various hash algorithms',
      arabicDescription: 'توليد HMAC باستخدام خوارزميات تجزئة مختلفة',
      category: ToolCategory.crypto,
      icon: Icons.token,
      route: '/tool_runner',
      parameters: {'message': '', 'key': '', 'algorithm': 'SHA256'},
    ),
    Tool(
      id: 'jwt_decoder',
      name: 'JWT Decoder',
      arabicName: 'فك تشفير JWT',
      description: 'Decode and inspect JWT tokens',
      arabicDescription: 'فك ترميز وفحص رموز JWT',
      category: ToolCategory.crypto,
      icon: Icons.badge,
      route: '/tool_runner',
      parameters: {'token': ''},
    ),
    Tool(
      id: 'password_generator',
      name: 'Password Generator',
      arabicName: 'مولد كلمات المرور',
      description: 'Generate strong random passwords',
      arabicDescription: 'توليد كلمات مرور قوية عشوائية',
      category: ToolCategory.crypto,
      icon: Icons.auto_fix_high,
      route: '/tool_runner',
      parameters: {'length': '16', 'includeSymbols': 'true'},
    ),
    Tool(
      id: 'password_strength',
      name: 'Password Strength',
      arabicName: 'فاحص قوة كلمة المرور',
      description: 'Analyze password strength and provide feedback',
      arabicDescription: 'تحليل قوة كلمة المرور وتقديم ملاحظات',
      category: ToolCategory.crypto,
      icon: Icons.shield,
      route: '/tool_runner',
      parameters: {'password': ''},
    ),
    Tool(
      id: 'random_bytes',
      name: 'Random Bytes',
      arabicName: 'مولد بايتات عشوائية',
      description: 'Generate cryptographically secure random bytes',
      arabicDescription: 'توليد بايتات عشوائية آمنة تشفيرياً',
      category: ToolCategory.crypto,
      icon: Icons.shuffle,
      route: '/tool_runner',
      parameters: {'length': '32'},
    ),
    Tool(
      id: 'xor_cipher',
      name: 'XOR Cipher',
      arabicName: 'شيفرة XOR',
      description: 'Encrypt/decrypt using XOR cipher',
      arabicDescription: 'التشفير/فك التشفير باستخدام شيفرة XOR',
      category: ToolCategory.crypto,
      icon: Icons.explicit,
      route: '/tool_runner',
      parameters: {'input': '', 'key': ''},
    ),
    Tool(
      id: 'caesar_cipher',
      name: 'Caesar Cipher',
      arabicName: 'شيفرة قيصر',
      description: 'Encrypt/decrypt using Caesar cipher',
      arabicDescription: 'التشفير/فك التشفير باستخدام شيفرة قيصر',
      category: ToolCategory.crypto,
      icon: Icons.rotate_right,
      route: '/tool_runner',
      parameters: {'input': '', 'shift': '3', 'mode': 'encrypt'},
    ),
    Tool(
      id: 'vigenere_cipher',
      name: 'Vigenere Cipher',
      arabicName: 'شيفرة فيجنير',
      description: 'Encrypt/decrypt using Vigenere cipher',
      arabicDescription: 'التشفير/فك التشفير باستخدام شيفرة فيجنير',
      category: ToolCategory.crypto,
      icon: Icons.text_rotation_none,
      route: '/tool_runner',
      parameters: {'input': '', 'key': '', 'mode': 'encrypt'},
    ),
    Tool(
      id: 'morse_encoder',
      name: 'Morse Encoder',
      arabicName: 'ترميز مورس',
      description: 'Encode text to Morse code',
      arabicDescription: 'ترميز النص إلى شفرة مورس',
      category: ToolCategory.crypto,
      icon: Icons.radio,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'morse_decoder',
      name: 'Morse Decoder',
      arabicName: 'فك ترميز مورس',
      description: 'Decode Morse code to text',
      arabicDescription: 'فك ترميز شفرة مورس إلى نص',
      category: ToolCategory.crypto,
      icon: Icons.radio_button_checked,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'url_encoder',
      name: 'URL Encoder',
      arabicName: 'ترميز URL',
      description: 'Encode text for URL safety',
      arabicDescription: 'ترميز النص للأمان في URL',
      category: ToolCategory.crypto,
      icon: Icons.link,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'url_decoder',
      name: 'URL Decoder',
      arabicName: 'فك ترميز URL',
      description: 'Decode URL-encoded text',
      arabicDescription: 'فك ترميز نص URL',
      category: ToolCategory.crypto,
      icon: Icons.link_off,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'hex_encoder',
      name: 'Hex Encoder',
      arabicName: 'ترميز Hex',
      description: 'Encode text to hexadecimal',
      arabicDescription: 'ترميز النص إلى نظام العد الست عشري',
      category: ToolCategory.crypto,
      icon: Icons.looks_one,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'hex_decoder',
      name: 'Hex Decoder',
      arabicName: 'فك ترميز Hex',
      description: 'Decode hexadecimal to text',
      arabicDescription: 'فك ترميز الست عشري إلى نص',
      category: ToolCategory.crypto,
      icon: Icons.looks_two,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'rot13',
      name: 'ROT13',
      arabicName: 'ترميز ROT13',
      description: 'Apply ROT13 substitution cipher',
      arabicDescription: 'تطبيق شيفرة الاستبدال ROT13',
      category: ToolCategory.crypto,
      icon: Icons.rotate_90_degrees_ccw,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),

    // ═══════════════════════════════════════════════════════════
    // CATEGORY 3: Web Tools (25 tools)
    // ═══════════════════════════════════════════════════════════
    Tool(
      id: 'html_minifier',
      name: 'HTML Minifier',
      arabicName: 'مصغر HTML',
      description: 'Minify HTML code by removing whitespace',
      arabicDescription: 'تصغير كود HTML بإزالة المسافات',
      category: ToolCategory.web,
      icon: Icons.code_off,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'css_minifier',
      name: 'CSS Minifier',
      arabicName: 'مصغر CSS',
      description: 'Minify CSS code',
      arabicDescription: 'تصغير كود CSS',
      category: ToolCategory.web,
      icon: Icons.style,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'js_minifier',
      name: 'JS Minifier',
      arabicName: 'مصغر JavaScript',
      description: 'Minify JavaScript code',
      arabicDescription: 'تصغير كود JavaScript',
      category: ToolCategory.web,
      icon: Icons.javascript,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'json_formatter',
      name: 'JSON Formatter',
      arabicName: 'منسق JSON',
      description: 'Format and validate JSON data',
      arabicDescription: 'تنسيق والتحقق من صحة بيانات JSON',
      category: ToolCategory.web,
      icon: Icons.data_object,
      route: '/tool_runner',
      parameters: {'input': '', 'mode': 'format'},
    ),
    Tool(
      id: 'xml_formatter',
      name: 'XML Formatter',
      arabicName: 'منسق XML',
      description: 'Format and validate XML data',
      arabicDescription: 'تنسيق والتحقق من صحة بيانات XML',
      category: ToolCategory.web,
      icon: Icons.code,
      route: '/tool_runner',
      parameters: {'input': '', 'mode': 'format'},
    ),
    Tool(
      id: 'http_request_builder',
      name: 'HTTP Request Builder',
      arabicName: 'باني طلبات HTTP',
      description: 'Build and send HTTP requests',
      arabicDescription: 'بناء وإرسال طلبات HTTP',
      category: ToolCategory.web,
      icon: Icons.build,
      route: '/tool_runner',
      parameters: {
        'url': '',
        'method': 'GET',
        'headers': '',
        'body': ''
      },
    ),
    Tool(
      id: 'api_tester',
      name: 'API Tester',
      arabicName: 'مختبر API',
      description: 'Test REST API endpoints',
      arabicDescription: 'اختبار نقاط نهاية REST API',
      category: ToolCategory.web,
      icon: Icons.api,
      route: '/tool_runner',
      parameters: {'url': '', 'method': 'GET'},
    ),
    Tool(
      id: 'cookie_parser',
      name: 'Cookie Parser',
      arabicName: 'محلل الكوكيز',
      description: 'Parse and analyze HTTP cookies',
      arabicDescription: 'تحليل وفحص كوكيز HTTP',
      category: ToolCategory.web,
      icon: Icons.cookie,
      route: '/tool_runner',
      parameters: {'cookies': ''},
    ),
    Tool(
      id: 'user_agent_switcher',
      name: 'User-Agent Switcher',
      arabicName: 'مبدل User-Agent',
      description: 'Generate and test different User-Agent strings',
      arabicDescription: 'توليد واختبار سلاسل User-Agent مختلفة',
      category: ToolCategory.web,
      icon: Icons.phonelink,
      route: '/tool_runner',
      parameters: {'agent': 'Chrome'},
    ),
    Tool(
      id: 'redirect_checker',
      name: 'Redirect Checker',
      arabicName: 'فاحص إعادة التوجيه',
      description: 'Follow and analyze URL redirects',
      arabicDescription: 'تتبع وتحليل إعادة توجيه URL',
      category: ToolCategory.web,
      icon: Icons.redo,
      route: '/tool_runner',
      parameters: {'url': ''},
    ),
    Tool(
      id: 'meta_tag_extractor',
      name: 'Meta Tag Extractor',
      arabicName: 'مستخرج الوسوم الوصفية',
      description: 'Extract meta tags from HTML',
      arabicDescription: 'استخراج الوسوم الوصفية من HTML',
      category: ToolCategory.web,
      icon: Icons.label,
      route: '/tool_runner',
      parameters: {'url': ''},
    ),
    Tool(
      id: 'email_extractor',
      name: 'Email Extractor',
      arabicName: 'مستخرج البريد الإلكتروني',
      description: 'Extract email addresses from text',
      arabicDescription: 'استخراج عناوين البريد الإلكتروني من النص',
      category: ToolCategory.web,
      icon: Icons.alternate_email,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'link_extractor',
      name: 'Link Extractor',
      arabicName: 'مستخرج الروابط',
      description: 'Extract URLs from text',
      arabicDescription: 'استخراج الروابط من النص',
      category: ToolCategory.web,
      icon: Icons.link,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'sitemap_generator',
      name: 'Sitemap Generator',
      arabicName: 'مولد خريطة الموقع',
      description: 'Generate XML sitemap from URL list',
      arabicDescription: 'توليد خريطة موقع XML من قائمة روابط',
      category: ToolCategory.web,
      icon: Icons.map,
      route: '/tool_runner',
      parameters: {'urls': ''},
    ),
    Tool(
      id: 'robots_txt_parser',
      name: 'Robots.txt Parser',
      arabicName: 'محلل Robots.txt',
      description: 'Parse and analyze robots.txt files',
      arabicDescription: 'تحليل وفحص ملفات robots.txt',
      category: ToolCategory.web,
      icon: Icons.pets,
      route: '/tool_runner',
      parameters: {'url': ''},
    ),
    Tool(
      id: 'favicon_extractor',
      name: 'Favicon Extractor',
      arabicName: 'مستخرج الأيقونة المفضلة',
      description: 'Extract favicon from websites',
      arabicDescription: 'استخراج الأيقونة المفضلة من المواقع',
      category: ToolCategory.web,
      icon: Icons.image,
      route: '/tool_runner',
      parameters: {'url': ''},
    ),
    Tool(
      id: 'color_picker',
      name: 'Color Picker',
      arabicName: 'منتقي الألوان',
      description: 'Pick and convert between color formats',
      arabicDescription: 'اختيار الألوان والتحويل بين التنسيقات',
      category: ToolCategory.web,
      icon: Icons.colorize,
      route: '/tool_runner',
      parameters: {'hex': '#00E676'},
    ),
    Tool(
      id: 'markdown_preview',
      name: 'Markdown Preview',
      arabicName: 'معاينة Markdown',
      description: 'Preview rendered Markdown',
      arabicDescription: 'معاينة Markdown المُصيَّر',
      category: ToolCategory.web,
      icon: Icons.preview,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'diff_checker',
      name: 'Diff Checker',
      arabicName: 'مدقق الفروقات',
      description: 'Compare two texts and show differences',
      arabicDescription: 'مقارنة نصين وعرض الاختلافات',
      category: ToolCategory.web,
      icon: Icons.compare_arrows,
      route: '/tool_runner',
      parameters: {'text1': '', 'text2': ''},
    ),
    Tool(
      id: 'lorem_ipsum_generator',
      name: 'Lorem Ipsum Generator',
      arabicName: 'مولد نصوص Lorem Ipsum',
      description: 'Generate Lorem Ipsum placeholder text',
      arabicDescription: 'توليد نص Lorem Ipsum وهمي',
      category: ToolCategory.web,
      icon: Icons.text_fields,
      route: '/tool_runner',
      parameters: {'paragraphs': '3'},
    ),
    Tool(
      id: 'slug_generator',
      name: 'Slug Generator',
      arabicName: 'مولد الروابط النصية',
      description: 'Generate URL-friendly slugs from text',
      arabicDescription: 'توليد روابط نصية صديقة للURL',
      category: ToolCategory.web,
      icon: Icons.text_snippet,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'qr_code_generator',
      name: 'QR Code Generator',
      arabicName: 'مولد رمز QR',
      description: 'Generate QR codes from text or URLs',
      arabicDescription: 'توليد رموز QR من نص أو روابط',
      category: ToolCategory.web,
      icon: Icons.qr_code,
      route: '/tool_runner',
      parameters: {'data': '', 'size': '200'},
    ),
    Tool(
      id: 'qr_code_reader',
      name: 'QR Code Reader',
      arabicName: 'قارئ رمز QR',
      description: 'Decode QR code data from image',
      arabicDescription: 'فك بيانات رمز QR من صورة',
      category: ToolCategory.web,
      icon: Icons.qr_code_scanner,
      route: '/tool_runner',
      parameters: {'image': ''},
    ),
    Tool(
      id: 'barcode_generator',
      name: 'Barcode Generator',
      arabicName: 'مولد الباركود',
      description: 'Generate various barcode formats',
      arabicDescription: 'توليد تنسيقات باركود مختلفة',
      category: ToolCategory.web,
      icon: Icons.barcode_reader,
      route: '/tool_runner',
      parameters: {'data': '', 'format': 'Code128'},
    ),
    Tool(
      id: 'barcode_reader',
      name: 'Barcode Reader',
      arabicName: 'قارئ الباركود',
      description: 'Read barcode data from image',
      arabicDescription: 'قراءة بيانات الباركود من صورة',
      category: ToolCategory.web,
      icon: Icons.barcode_reader,
      route: '/tool_runner',
      parameters: {'image': ''},
    ),

    // ═══════════════════════════════════════════════════════════
    // CATEGORY 4: Forensics Tools (25 tools)
    // ═══════════════════════════════════════════════════════════
    Tool(
      id: 'file_hash_calculator',
      name: 'File Hash Calculator',
      arabicName: 'حاسبة تجزئة الملفات',
      description: 'Calculate MD5, SHA1, SHA256 hashes of file content',
      arabicDescription: 'حساب تجزئات MD5 وSHA1 وSHA256 لمحتوى الملف',
      category: ToolCategory.forensics,
      icon: Icons.tag,
      route: '/tool_runner',
      parameters: {'input': '', 'algorithm': 'SHA256'},
    ),
    Tool(
      id: 'metadata_extractor',
      name: 'Metadata Extractor',
      arabicName: 'مستخرج البيانات الوصفية',
      description: 'Extract metadata from files and images',
      arabicDescription: 'استخراج البيانات الوصفية من الملفات والصور',
      category: ToolCategory.forensics,
      icon: Icons.description,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'exif_viewer',
      name: 'EXIF Viewer',
      arabicName: 'عارض EXIF',
      description: 'View EXIF data from images',
      arabicDescription: 'عرض بيانات EXIF من الصور',
      category: ToolCategory.forensics,
      icon: Icons.camera_alt,
      route: '/tool_runner',
      parameters: {'image': ''},
    ),
    Tool(
      id: 'strings_extractor',
      name: 'Strings Extractor',
      arabicName: 'مستخرج السلاسل النصية',
      description: 'Extract readable strings from binary data',
      arabicDescription: 'استخراج السلاسل القابلة للقراءة من البيانات الثنائية',
      category: ToolCategory.forensics,
      icon: Icons.text_format,
      route: '/tool_runner',
      parameters: {'input': '', 'minLength': '4'},
    ),
    Tool(
      id: 'hex_viewer',
      name: 'Hex Viewer',
      arabicName: 'عارض Hex',
      description: 'View data in hexadecimal format',
      arabicDescription: 'عرض البيانات بتنسيق الست عشري',
      category: ToolCategory.forensics,
      icon: Icons.view_column,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'binwalk',
      name: 'Binwalk Scanner',
      arabicName: 'ماسح توقيعات الملفات',
      description: 'Scan for embedded file signatures in data',
      arabicDescription: 'مسح توقيعات الملفات المضمنة في البيانات',
      category: ToolCategory.forensics,
      icon: Icons.find_in_page,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'steg_detector',
      name: 'Steganography Detector',
      arabicName: 'مكتشف الإخفاء',
      description: 'Detect hidden data in images (steganography)',
      arabicDescription: 'اكتشاف البيانات المخفية في الصور',
      category: ToolCategory.forensics,
      icon: Icons.visibility_off,
      route: '/tool_runner',
      parameters: {'image': ''},
    ),
    Tool(
      id: 'steg_image_embed',
      name: 'Steg Image Embed',
      arabicName: 'تضمين صورة داخل صورة',
      description: 'Hide data inside an image using LSB steganography',
      arabicDescription: 'إخفاء بيانات داخل صورة باستخدام LSB',
      category: ToolCategory.forensics,
      icon: Icons.image_search,
      route: '/tool_runner',
      parameters: {'carrier': '', 'payload': ''},
    ),
    Tool(
      id: 'steg_image_extract',
      name: 'Steg Image Extract',
      arabicName: 'استخراج صورة مخفية',
      description: 'Extract hidden data from steganographic images',
      arabicDescription: 'استخراج البيانات المخفية من الصور',
      category: ToolCategory.forensics,
      icon: Icons.image_aspect_ratio,
      route: '/tool_runner',
      parameters: {'image': ''},
    ),
    Tool(
      id: 'file_carver',
      name: 'File Carver',
      arabicName: 'نحات الملفات',
      description: 'Carve files from binary data based on signatures',
      arabicDescription: 'نحت الملفات من البيانات الثنائية بناءً على التوقيعات',
      category: ToolCategory.forensics,
      icon: Icons.content_cut,
      route: '/tool_runner',
      parameters: {'input': ''},
    ),
    Tool(
      id: 'memory_dump_analyzer',
      name: 'Memory Dump Analyzer',
      arabicName: 'محلل تفريغ الذاكرة',
      description: 'Analyze memory dump strings and patterns',
      arabicDescription: 'تحليل سلاسل وأنماط تفريغ الذاكرة',
      category: ToolCategory.forensics,
      icon: Icons.memory,
      route: '/tool_runner',
      parameters: {'dump': ''},
    ),
    Tool(
      id: 'registry_parser',
      name: 'Registry Parser',
      arabicName: 'محلل سجل النظام',
      description: 'Parse Windows registry hive files',
      arabicDescription: 'تحليل ملفات خلية سجل Windows',
      category: ToolCategory.forensics,
      icon: Icons.app_registration,
      route: '/tool_runner',
      parameters: {'hive': ''},
    ),
    Tool(
      id: 'prefetch_parser',
      name: 'Prefetch Parser',
      arabicName: 'محلل Prefetch',
      description: 'Parse Windows Prefetch files',
      arabicDescription: 'تحليل ملفات Prefetch في Windows',
      category: ToolCategory.forensics,
      icon: Icons.speed,
      route: '/tool_runner',
      parameters: {'prefetch': ''},
    ),
    Tool(
      id: 'lnk_parser',
      name: 'LNK Parser',
      arabicName: 'محلل ملفات LNK',
      description: 'Parse Windows shortcut (LNK) files',
      arabicDescription: 'تحليل ملفات الاختصار LNK في Windows',
      category: ToolCategory.forensics,
      icon: Icons.shortcut,
      route: '/tool_runner',
      parameters: {'lnk': ''},
    ),
    Tool(
      id: 'email_header_analyzer',
      name: 'Email Header Analyzer',
      arabicName: 'محلل رؤوس البريد الإلكتروني',
      description: 'Analyze email headers for routing and authenticity',
      arabicDescription: 'تحليل رؤوس البريد الإلكتروني للتوجيه والمصداقية',
      category: ToolCategory.forensics,
      icon: Icons.mark_email_read,
      route: '/tool_runner',
      parameters: {'headers': ''},
    ),
    Tool(
      id: 'log_file_analyzer',
      name: 'Log File Analyzer',
      arabicName: 'محلل ملفات السجل',
      description: 'Parse and analyze log files',
      arabicDescription: 'تحليل وقراءة ملفات السجل',
      category: ToolCategory.forensics,
      icon: Icons.assignment,
      route: '/tool_runner',
      parameters: {'log': ''},
    ),
    Tool(
      id: 'timeline_generator',
      name: 'Timeline Generator',
      arabicName: 'مولد الخط الزمني',
      description: 'Generate forensic timeline from events',
      arabicDescription: 'توليد خط زمني جنائي من الأحداث',
      category: ToolCategory.forensics,
      icon: Icons.timeline,
      route: '/tool_runner',
      parameters: {'events': ''},
    ),
    Tool(
      id: 'data_wiper',
      name: 'Data Wiper',
      arabicName: 'ماسح البيانات',
      description: 'Generate secure wipe patterns (Gutmann, DoD)',
      arabicDescription: 'توليد أنماط مسح آمن للبيانات',
      category: ToolCategory.forensics,
      icon: Icons.delete_forever,
      route: '/tool_runner',
      parameters: {'passes': '7', 'pattern': 'DoD'},
    ),
    Tool(
      id: 'file_recovery',
      name: 'File Recovery',
      arabicName: 'استعادة الملفات',
      description: 'Simulate file recovery from lost data',
      arabicDescription: 'محاكاة استعادة الملفات من البيانات المفقودة',
      category: ToolCategory.forensics,
      icon: Icons.restore_page,
      route: '/tool_runner',
      parameters: {'signature': ''},
    ),
    Tool(
      id: 'disk_imager',
      name: 'Disk Imager',
      arabicName: 'تصوير القرص',
      description: 'Generate disk image metadata and hash verification',
      arabicDescription: 'توليد بيانات وصفية لصورة القرص والتحقق',
      category: ToolCategory.forensics,
      icon: Icons.storage,
      route: '/tool_runner',
      parameters: {'size': '', 'hash': ''},
    ),
    Tool(
      id: 'partition_analyzer',
      name: 'Partition Analyzer',
      arabicName: 'محلل الأقسام',
      description: 'Analyze partition table structures',
      arabicDescription: 'تحليل هياكل جدول الأقسام',
      category: ToolCategory.forensics,
      icon: Icons.view_list,
      route: '/tool_runner',
      parameters: {'mbr': ''},
    ),
    Tool(
      id: 'usb_history',
      name: 'USB History',
      arabicName: 'تاريخ USB',
      description: 'Parse USB device connection history',
      arabicDescription: 'تحليل سجل توصيل أجهزة USB',
      category: ToolCategory.forensics,
      icon: Icons.usb,
      route: '/tool_runner',
      parameters: {'registry': ''},
    ),
    Tool(
      id: 'browser_history',
      name: 'Browser History',
      arabicName: 'تاريخ المتصفح',
      description: 'Parse browser history data',
      arabicDescription: 'تحليل بيانات سجل المتصفح',
      category: ToolCategory.forensics,
      icon: Icons.web_asset,
      route: '/tool_runner',
      parameters: {'history': ''},
    ),
    Tool(
      id: 'clipboard_viewer',
      name: 'Clipboard Viewer',
      arabicName: 'عارض الحافظة',
      description: 'View and analyze clipboard content history',
      arabicDescription: 'عرض وتحليل محتوى الحافظة',
      category: ToolCategory.forensics,
      icon: Icons.content_paste,
      route: '/tool_runner',
      parameters: {'data': ''},
    ),
    Tool(
      id: 'recent_files',
      name: 'Recent Files',
      arabicName: 'الملفات الأخيرة',
      description: 'Analyze recent files accessed on the system',
      arabicDescription: 'تحليل الملفات المستخدمة مؤخراً',
      category: ToolCategory.forensics,
      icon: Icons.access_time,
      route: '/tool_runner',
      parameters: {'recent': ''},
    ),
  ];

  /// Get tools filtered by category
  static List<Tool> getByCategory(ToolCategory category) {
    return allTools.where((t) => t.category == category).toList();
  }

  /// Get a single tool by its ID
  static Tool? getById(String id) {
    try {
      return allTools.firstWhere((t) => t.id == id);
    } catch (_) {
      return null;
    }
  }

  /// Search tools by name or description (case-insensitive)
  static List<Tool> search(String query) {
    final lowerQuery = query.toLowerCase();
    return allTools.where((t) {
      return t.name.toLowerCase().contains(lowerQuery) ||
          t.arabicName.contains(query) ||
          t.description.toLowerCase().contains(lowerQuery) ||
          t.arabicDescription.contains(query);
    }).toList();
  }

  /// Get count of tools per category
  static Map<ToolCategory, int> get categoryCounts {
    final counts = <ToolCategory, int>{};
    for (final category in ToolCategory.values) {
      counts[category] = getByCategory(category).length;
    }
    return counts;
  }

  /// Total number of registered tools
  static int get totalToolCount => allTools.length;

  /// Get number of implemented vs total tools
  static int get implementedCount =>
      allTools.where((t) => t.isImplemented).length;
}
